### ISSUE TITLE
Reading material listed on Introductory page bundled with latest Toolbox

### ISSUE THREAD

**Issue by lemmy** [hwayne/learntla#39]
The external reading material listed on https://learntla.com/introduction/about-this-guide/ is bundled with the TLAToolbox version 1.5.4 onwards. You might want to inform readers.

**Comment by hwayne** [comment]
Will do!

**Comment by hwayne** [comment]
Fixed in https://github.com/hwayne/learntla/commit/31b6232925e28054d1dbd9607fd5614a112a1d65.
