### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [hwayne/learntla#46]
Looking at the site itself (https://www.learntla.com/introduction/), it says in the upper-left corner:

>  This work is licensed under a Creative Commons Attribution 4.0 International License.

So you probably want to add the contents of [this URL](https://creativecommons.org/licenses/by/4.0/legalcode.txt) as the file `LICENSE` in your repo so that it's obvious and GitHub will recognize it and mark the repo as such.

Without having a license file, it's unclear to folks who only see the GitHub repo and not the site what the license of the repo's content is, and whether or not they can contribute patches or reuse the content — which, in the absence of a license, they cannot by default — the absence of a license implies "all rights reserved", at least in some countries.

**Comment by hwayne** [comment]
Thanks for the catch! Just added the license now.
