### ISSUE TITLE
Dead link on "Using the Toolbox"

### ISSUE THREAD

**Issue by YoranBrondsema** [hwayne/learntla#52]
The link [TLA+ Toolbox](https://research.microsoft.com/en-us/um/people/lamport/tla/toolbox.html) in the first paragraph of https://learntla.com/pluscal/toolbox/ is dead (400 Bad Request). I'm not sure what was there before but maybe it can be replaced with http://lamport.azurewebsites.net/tla/toolbox.html?

**Comment by hwayne** [comment]
That's odd, it's working for me. Can you confirm that it's still broken on your end?

**Comment by YoranBrondsema** [comment]
Ah, my bad. It looks like the HTTPS Everywhere extension is causing the error.
