### ISSUE TITLE
Bogus example assigning to (constant) bound identifier

### ISSUE THREAD

**Issue by lemmy** [hwayne/learntla#57]
The example below (copied from https://learntla.com/pluscal/behaviors/) is bogus and future Pcal translator versions won't accept it (see screenshot below). The "f" in the either statement is a bound identifier and thus cannot be assigned a value.

```tla
---- MODULE flags ----
EXTENDS TLC, Integers
(* --algorithm flags
variables f1 \in BOOLEAN, f2 \in BOOLEAN, f3 \in BOOLEAN
begin
  while TRUE do
    with f \in {f1, f2, f3} do
      either
        f := TRUE;
      or
        f := FALSE;
      end either;
    end with;
  end while;
end algorithm; *)

====
```

![assignmenttoundeclaredvar](https://user-images.githubusercontent.com/88777/40136438-729ebe42-5937-11e8-9e55-d29daf1d8e2c.png)

**Comment by hwayne** [comment]
Working on a fixed version

**Comment by hwayne** [comment]
A stopgap is up for now that is fixed
