### ISSUE TITLE
Exercise after explanation of "=>" and "<=>" requires use of "<="

### ISSUE THREAD

**Issue by ajdavis** [hwayne/learntla#69]
The exercise on https://learntla.com/tla/logic/ that follows the explanation of "=> and <=>" requires this answer:
```
Max(S) == CHOOSE x \in S : \A y \in S : y <= x
```
This is confusing, because the section has explained logic operators, but the exercise is about the mathematical comparison "<=" (less than or equal to).

**Comment by hwayne** [comment]
Ooof. I don't even know where that was supposed to be. Maybe one section up?
