### ISSUE TITLE
About the with behavior on set containing duplicated elements

### ISSUE THREAD

**Issue by PineWu** [hwayne/learntla#80]
When performing on set containing duplicated elements, I found that `with` only creates a behavior for each **distinct** element in the set.
`with a \in {1, 1, 2,2, 3,3} do
    print a;
end with`
The output will be: 1, 2, 3
Is my understanding right? If so, I think it's better to emphasize this behavior.

**Comment by hwayne** [comment]
That's because sets only consist of unique elements. try putting `{1, 1, 1, 1, 1, 1}` into the evaluator: it should output `{1}`.

**Comment by PineWu** [comment]
> That's because sets only consist of unique elements. try putting `{1, 1, 1, 1, 1, 1}` into the evaluator: it should output `{1}`.

Got it. Thanks much~
