### ISSUE TITLE
Deployed version not up-to-date with repository

### ISSUE THREAD

**Issue by felixlinker** [hwayne/learntla#99]
I was about to open an issue that https://learntla.com/introduction/about-this-guide/ points to an outdated version of the PlusCal manual, however, 49a0b465865a20e0c9c22cd9376ab54295d450db fixed this problem.

Yet, still, the link for me points to https://research.microsoft.com/en-us/um/people/lamport/tla/pluscal.html

I tried `Ctrl+Shift+R`-refreshing the page.

**Comment by hwayne** [comment]
Yeah, I'm really behind on updating learntla. ACKing that this is a 
problem and that I intend to fix it

**Comment by link2xt** [comment]
Any update on this? The link on https://www.learntla.com/introduction/about-this-guide/ is still wrong.

**Comment by link2xt** [comment]
As a workaround I installed `hugo`, set `relativeURLs = true` and built a locally readable version.

**Comment by hwayne** [comment]
I'll, um, try to get it done beforetheendoftheyear

**Comment by hwayne** [comment]
DONE

**Comment by link2xt** [comment]
Thanks!
